CC = g++ CFLAGS = `pkg - config-- cflags-- libs gtkmm - 3.0` SRCS =
    main.cc gui.cc

        TARGET = deny -
                 descriptor

                     all : $(CC) $(CFLAGS) $(SRCS) -
                           o $(TARGET)

                               clean : rm -
                                       f $(TARGET)
