name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup OpenCV
      uses: Dovyski/setup-opencv-action@v1
    - name: Build Descriptor
      run: make -C descriptor/
    - name: Build Dumper
      run: make -C dumper/
